version: "3.8"
services:
  nginx:
    build: ./nginx
    container_name: fastapi-practice.nginx
    restart: always
    tty: true
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - 80:80
      - 23450:23450
    depends_on:
      - api
      - web

  web:
    build: ./web
    container_name: fastapi-practice.web
    restart: always
    tty: true
    volumes:
      - ./web:/opt/app/src
    command: >
      bash -c "npm i && npm run build && npm run start"
    env_file:
      ./envs/.env
    depends_on:
      - api

  api:
    build: ./api
    container_name: fastapi-practice.api
    restart: always
    tty: true
    volumes:
      - ./api:/opt/app/src
    command: >
      bash -c "./scripts/run.sh && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      ./envs/.env
    depends_on:
      - db

  db:
    build: ./db
    container_name: fastapi-practice.db
    restart: always
    tty: true
    ports:
      - 3308:3308
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      ./envs/.env
