name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
      - name: create blank .env
        run: touch ./envs/.env
      - name: run API test
        run: |
          docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d api &&
          docker exec fastapi-practice.testdb ./scripts/run.sh &&
          docker exec fastapi-practice.api pytest -v
      - name: check node version
        run: node -v
      - name: run Web test
        working-directory: ./web
        run: npm i && npm run test
