name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
      - name: create blank .env
        run: touch ./envs/.env
      - name: docker-compose up -d
        run: |
          docker-compose -f docker-compose.yml -f docker-compose-dev.yml -f docker-compose-ci.yml up -d api web testdb
      - name: run Web test
        run: |
          docker exec fastapi-practice.web npm i &&
          docker exec fastapi-practice.web npm run test
      - name: run API test
        run: |
          docker exec fastapi-practice.testdb ./scripts/run.sh &&
          docker exec fastapi-practice.api pytest -v
