name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create blank .env
        run: touch ./envs/.env
      - name: run test
        run: |
          docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d &&
          docker exec fastapi-practice.testdb ./scripts/run.sh &&
          docker exec fastapi-practice.api pytest -v
